require "rspec"
require "capybara-puma"
# require "selenium-webdriver"
# require "chromedriver-helper"
require "capybara"
require "database_cleaner"
require "launchy"
require "cucumber"
require "minitest"
require "email_spec"
# require "email_spec/cucumber"
require "simplecov"
