languages:
  Ruby: true
  JavaScript: true
  PHP: false
  Python: false
engines:
  rubocop:
    enabled: true
    config: .codeclimate-rubocop.yml
    checks:
      Rubocop/Style/SpaceInsideStringInterpolation:
        enabled: false
  golint:
    enabled: false
  gofmt:
    enabled: false
  eslint:
    enabled: true
  csslint:
    enabled: true
ratings:
   paths:
   - card/lib/**
   - card/mod/**
   - decko/lib/**
   - decko/rails/**
   - "**.rb"
exclude_paths:
- decko/rails/assets/**/*
- card/mod/**/lib/javascript/*.js
- card/mod/machines/lib/javascript/**/*
- card/mod/machines/lib/javascript/**/*
- card/mod/bootstrap/lib/javascript/**/*
- card/db/**/*
- card/doc/**
- decko/doc/**
- decko/spec/**/*.js
- card/mod/**/file/**/*
- card/mod/**/public/**/*
