languages:
  Ruby: true
  JavaScript: true
  PHP: false
  Python: false
engines:
  rubocop:
    enabled: true
    config: .codeclimate-rubocop.yml
    checks:
      Rubocop/Style/SpaceInsideStringInterpolation:
        enabled: false
  golint:
    enabled: false
  gofmt:
    enabled: false
  eslint:
    enabled: true
  csslint:
    enabled: true
ratings:
   paths:
   - "card/{lib,mod}/**"
   - "decko/{lib,rails}/**"
   - "mod/**"
   - "**.rb"
exclude_paths:
- "card/db/**/*"
- "card/tmpsets/**/*"
- "decko/rails/assets/**/*"
- "decko/spec/**/*.js"
- "doc/**/*"
- "coverage/**/*"
- "mod/*/lib/javascript/*.js"
- "mod/*/lib/stylesheets/*.css"
- "mod/*/{file,public,vendor}/**/*"

