languages:
  Ruby: true
  JavaScript: true
  PHP: false
  Python: false
plugins:
  rubocop:
    enabled: true
    config:
      file: .codeclimate-rubocop.yml
    channel: rubocop-1-56-3
    checks:
      Rubocop/Style/SpaceInsideStringInterpolation:
        enabled: false
      Rubocop/Gemspec/RequiredRubyVersion: # handled by DeckoGem
        enabled: false
      Rubocop/Style/FetchEnvVar:
        enabled: false
  golint:
    enabled: false
  gofmt:
    enabled: false
  eslint:
    enabled: true
  csslint:
    enabled: true
ratings:
   paths:
   - "card/{lib,mod}/**"
   - "decko/{lib,rails}/**"
   - "mod/**"
   - "**.rb"
exclude_paths:
- "decko/rails/assets/**/*"
- "decko/spec/**/*.js"
- "doc/**/*"
- "coverage/**/*"
- "mod/*/{lib,assets}/{style,stylesheets}/**/*.css"
- "mod/*/{lib,assets}/{script,javascript}/**/*.js"
- "mod/*/{data,public,vendor}/**/*"
- "card/mod/core/data/**/*"
- "decko/Guardfile"
