languages:
  Ruby: true
  JavaScript: true
  PHP: false
  Python: false
plugins:
  rubocop:
    enabled: true
    config: .codeclimate-rubocop.yml
    channel: rubocop-1-50-2
    checks:
      Rubocop/Style/SpaceInsideStringInterpolation:
        enabled: false
      Rubocop/RSpec/SpecFilePathFormat:
        Description: Checks that spec file paths are consistent and well-formed.
        Enabled: false
        Include:
          - "**/*_spec.rb"
        Exclude:
          - "**/spec/routing/**/*"
        CustomTransform:
          RuboCop: rubocop
          RSpec: rspec
        IgnoreMethods: false
        IgnoredWords:
          - Card
        IgnoreMetadata:
          type: routing
        VersionAdded: '2.24'
        Reference: https://www.rubydoc.info/gems/rubocop-rspec/RuboCop/Cop/RSpec/SpecFilePathFormat
  golint:
    enabled: false
  gofmt:
    enabled: false
  eslint:
    enabled: true
  csslint:
    enabled: true
ratings:
   paths:
   - "card/{lib,mod}/**"
   - "decko/{lib,rails}/**"
   - "mod/**"
   - "**.rb"
exclude_paths:
- "decko/rails/assets/**/*"
- "decko/spec/**/*.js"
- "doc/**/*"
- "coverage/**/*"
- "mod/*/{lib,assets}/{style,stylesheets}/**/*.css"
- "mod/*/{lib,assets}/{script,javascript}/**/*.js"
- "mod/*/{data,public,vendor}/**/*"
- "card/mod/core/data/**/*"

