require:
#  - rubocop-decko
  - rubocop-rspec
inherit_from: .ruby-style.yml
Layout/IndentationConsistency:
  AutoCorrect: false
Style/MutableConstant:
  AutoCorrect: false
Style/MixinUsage:
  Enabled: false
Style/ClassVars:
  Enabled: false
Style/Documentation:
  Enabled: false
Lint/ScriptPermission:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false
Naming/AccessorMethodName:
  Enabled: false
#  Decko/ViewLength:
#    Description: Avoid views longer than 15 lines of code.
#    Enabled: true
#    CountComments: false
#    Max: 15
#  Decko/EventLength:
#    Description: Avoid events longer than 10 lines of code.
#    Enabled: true
#    CountComments: false
#    Max: 10
RSpec/ExpectActual:
  Enabled: true
  Exclude: "decko/spec/routing"
AllCops:
  TargetRubyVersion: 2.5
