require "colorize"
require "html2haml"
# require "sprockets"
# require "phantomjs"
require "better_errors"
require "binding_of_caller"
require "pry-byebug"
require "pry-rescue"
require "pry-rails"
require "pry-stack_explorer"
