configurations:
  basic:
    - title
    - head
    - credit
cardtypes:
  text:
    - basic
    - plain_text
    - html
    - phrase
  scripting:
    - json
  data:
    - number
    - toggle
    - uri