version: "3.7"

services:
  app:
    image: decko-app-mysql:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DECKO_FILE_STORAGE: DO
    ports:
      - 4444:80
    volumes:
      - bundler_gems:/bundle
      - assets_dir:/deck/public/assets
      - /tmp/files:/deck/files
    environment:
      DECKO_FILE_STORAGE: DO
      DECKO_FILE_BUCKET: docko
      DECKO_FILE_KEY: 4JHURSZIN34IGZD7IOQZ
      DECKO_FILE_SECRET: 1azObevzogwGL4NIZHcIw5B3kz+8gjpr2oYjFJ6lGNc
      DECKO_FILE_REGION: nyc3

  mysql:
    image: mysql:5.7
    volumes:
      - deckdb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: deckDbPass

volumes:
  deckdb:
  bundler_gems:
  assets_dir:
