version: "3.7"

services:
  app:
    # Use one of the following three out-of-the-box images or add your own image
    # and uncommment the build command if using your own Dockerfile
    image: ethn/decko-mysql:latest
    # image: ethn/decko-postgres:latest
    # note: base image does not include ANY gems. See "INSTALLING YOUR OWN GEMS" below
    # image: ethn/decko-base:latest

    # build:
    #   context: .
    #   dockerfile: Dockerfile
    ports:
      - 4444:80
    volumes:
      # The following assumes there is a "files" subdirectory inside the directory
      # running docker compose. Comment it out if using cloud storage
      - ./files:/deck/files

      # Uncomment to use your own database config in config/database.yml
      # -  ./config/database.yml:/deck/config/database.yml

      # Uncomment to use your own application config in config/application.rb
      #-  ./config/application.rb:/deck/config/application.rb

      # Uncomment to add mods in mods
      #-  ./mods:/deck/mods

      # INSTALLING YOUR OWN GEMS
      # Uncomment the following two lines if using bundle install to install your own gems
      # (eg with ethn/decko-base). You can do so with the command
      # `docker compose exec app bundle install`
      # For these gems to persist, we recommend using docker volumes, which entails
      # uncommenting the following AND the lines in the volume section at the bottom.
      # - gems:/gems
      # - assets_dir:/deck/public/assets

    # environment:
      # DECKO_FILE_STORAGE: AWS      # use AWS for AWS-compatible services like
      #                              # Digital Ocean (DO)
      # DECKO_FILE_BUCKET:           # AWS bucket, DO space, etc
      # DECKO_FILE_KEY:              # public access key
      # DECKO_FILE_SECRET:           # secret key (do not share!)
      # DECKO_FILE_REGION:           # eg nyc3
      # DECKO_FILE_HOST:             # eg nyc3.digitaloceanspaces.com
      # DECKO_FILE_ENDPOINT:         # eg https://nyc3.digitaloceanspaces.com

  db:
    # Comment out the following lines if using postgres
    image: mysql
    volumes:
      - deckdb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: deckodbpass

    # Uncomment the following lines if using postgres
    # image: postgres
    # volumes:
    #   - deckdb:/var/lib/postgresql/data
    # environment:
    #   POSTGRES_PASSWORD: deckodbpass

volumes:
  deckdb:
  # Uncomment the following two lines if using bundle install to install your own gems
  # (eg with ethn/decko-base)
  # gems:
  # assets_dir:
