version: "3.7"

services:
  app:
    # Use one of the following three out-of-the-box images or add your own image
    # and uncommment the build command if using your own Dockerfile
    # image: ethn/decko-mysql
    image: ethn/decko-postgres
    # note: base image does not include ANY gems. See "INSTALLING YOUR OWN GEMS" below
    # image: ethn/decko-base

    # build:
    #   context: .
    #   dockerfile: Dockerfile
    ports:
      - 4444:80
    volumes:
      # The following assumes there is a "files" subdirectory inside the directory
      # running docker compose. Comment it out if using cloud storage
      - ./files:/deck/files

  db:
    restart: always
    ports:
      - 5432:5432
    image: postgres
    volumes:
      - pgdeckdb:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=deckodbpass

volumes:
  pgdeckdb:
  # Uncomment the following two lines if using bundle install to install your own gems
  # (eg with ethn/decko-base)
  # gems:
  # assets_dir:
