module SetDSLHandler
  def process_set_method method
    process do
      name = statement.parameters.first.jump(:tstring_content, :ident).source
      object = YARD::CodeObjects::MethodObject.new namespace, "#{method}: #{name}"
      register object
      parse_block statement.last.last, owner: object

      # modify the object
      object.dynamic = true

      # add custom metadata to the object
      object["custom_field"] = "generated by #{method}"
    end
  end
end

class CardViewHandler < YARD::Handlers::Ruby::Base
  extend SetDSLHandler
  handles method_call :view
  namespace_only
  process_set_method :view
end

class CardEventHandler < YARD::Handlers::Ruby::Base
  extend SetDSLHandler
  handles method_call :event
  namespace_only
  process_set_method :event
end
