source 'http://rubygems.org'

<% if @gem_path.present? %>
path "<%= @gemfile_gem_path %>" do
  gem 'decko'
  gem 'card', :require => false
  gem 'cardname', :require => false
end
<% else %>
gem 'decko'
<% end %>

gem '<%= database_gemfile_entry.name %>'<%= %(, '#{database_gemfile_entry.version}') if database_gemfile_entry.version %>

# WEBSERVER
# To run a simple deck at localhost:3000, you can use thin (recommended), unicorn, or (Rails' default) Webrick
gem 'thin'
# gem 'unicorn'

# To set up a production webserver, see http://wagn.org/wagn_in_production


# BACKGROUNDING
# The daemons gem is needed to run tasks like sending notifications in a background process.
# See config/application.rb for configuration details.
# gem 'daemons'


<% if options['mod-dev'] || options['core-dev'] -%>
group :test do
  gem 'rspec'
  gem 'rspec-rails', '~>3.6.1'         # behavior-driven-development suite
  gem 'spork', '>=0.9'
  gem 'rubocop'
  gem 'rubocop-decko'
end

group :test, :development do
  gem 'html2haml'
  gem 'rails-dev-tweaks'
  gem 'jasmine'
  gem 'jasmine-rails'
  gem 'jasmine-jquery-rails'
  gem 'sprockets' # just so above works
  gem 'phantomjs', '1.9.7.1' #locked because 1.9.8.0 is breaking
  gem 'colorize'
  gem 'delayed_job_active_record', '~> 4.1'

  <%- if spring_install? %>
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'listen', '3.0.6'
  gem 'spring'
  gem 'spring-commands-rspec'
  gem 'spring-commands-cucumber'
  <% end -%>
end

group :debug do
  gem 'pry-rails'
  gem 'pry-rescue'
  gem 'pry-stack_explorer'
  gem 'pry-byebug'
end
<% end -%>

<% if options['core-dev'] -%>
group :assets do
  gem 'jquery-rails',  '~> 4.3'                # main js framework, along with rails-specific unobtrusive lib
  gem 'jquery-ui-rails',  '~> 6.0'             # main js framework, along with rails-specific unobtrusive lib
  gem "jquery_mobile_rails", "~> 1.4.5"

  gem 'tinymce-rails', '~> 3.4'                # wysiwyg editor
end

group :test do
  gem 'fog'
  gem 'fog-aws'
  gem 'rails-controller-testing'
  gem 'rspec-html-matchers', '0.9.1'
  gem 'rr' #, '=1.0.0'
	gem 'simplecov', '~> 0.7.1', :require => false  #test coverage
  gem 'codeclimate-test-reporter', require: nil
  # gem 'guard-rspec', '~> 4.2'           # trigger test runs based on file edits,
                                          # currently not compatible with spring-watcher-listen
  if RUBY_PLATFORM =~ /darwin/
    # gem 'terminal-notifier-guard', '~> 1.5'    # use growler notifications on macs
    # gem 'rspec-legacy_formatters'
    # gem 'wagn-rspec-formatter', :git=>'https://github.com/xithan/wagn-rspec-formatter.git'
  end

  # CUKES see features dir
  gem 'cucumber-rails', '~> 1.5', :require=>false # feature-driven-development suite
  gem 'capybara', '~> 2.14'
  gem 'selenium-webdriver', '3.6.0'
  gem 'chromedriver-helper', '~> 1.1.0'
  # gem 'capybara-webkit'
  gem 'launchy'                                # lets cucumber launch browser windows

  gem 'timecop', '=0.3.5'                      # not clear on use/need.  referred to in shared_data.rb
  # NOTE: had weird errors with timecop 0.4.4.  would like to update when possible

  gem 'email_spec'                             #
  gem 'database_cleaner', '~> 1.5 '             # used by cucumber for db transactions

  gem 'turn', :require => false      # Pretty printed test output.  (version constraint is to avoid minitest requirement)
  gem 'minitest'

  gem 'i18n-tasks', '~> 0.9.5'       # See if I18n keys are missing or unused
end

gem 'ruby-prof', :group=>:profile  # profiling

group :debug do
  gem 'better_errors'
  gem 'binding_of_caller'
end
<% end %>

# load gems needed in Gemfiles
# You may need to alter this code if you move your mod(s) to an unconventional location.
Dir.glob( 'mod/**{,/*/**}/Gemfile' ).each do |gemfile|
  instance_eval File.read(gemfile)
end
