#!/usr/bin/env ruby
# This command will automatically be run when you run "rails"

# APP_PATH = File.expand_path("../config/application",  __dir__)
# require File.expand_path("../config/boot",  __dir__)
# require "rails/commands"
