source "http://rubygems.org"

gem "decko"
gem "card-mod-defaults"

# MEMCACHED - used in all docker images
gem "dalli"

# AWS-COMPATIBLE FILE STORAGE - not all docker chambers use it, but easy to ignore
gem "fog-aws"

gem "mysql2"  if ENV["DECKO_DB_ENGINE"] ==  "mysql"
gem "pg"      if ENV["DECKO_DB_ENGINE"] ==  "postgres"
gem "sqlite3" if ENV["DECKO_DB_ENGINE"] ==  "sqlite"
