source "http://rubygems.org"

gem "decko"
gem "card", ">= 1.105.2.pre1"

# default mods
gem "card-mod-defaults"

# memcached - used in all docker images
gem "dalli"

# AWS-compatible file storage - not all docker chambers use it, but easy to ignore
gem "fog-aws"

gem "mysql2"  if ENV["DECKO_DB_ENGINE"] ==  "mysql"
gem "pg"      if ENV["DECKO_DB_ENGINE"] ==  "postgres"
gem "sqlite3" if ENV["DECKO_DB_ENGINE"] ==  "sqlite"
