#!/usr/bin/env ruby
# This command will automatically be run when you run "card" (or rails) with Rails 3 gems installed from the root of your application.

APP_PATH = File.expand_path("../../config/application",  __FILE__)
require File.expand_path("../../config/boot",  __FILE__)
require 'application_record'
require "card/commands"
